from typing import Callable, Any

def measure(probe_name: str, array: list[int]) -> float: ...
def list_probes() -> list[str]: ...
def measure_all(array: list[int]) -> dict[str, float]: ...
def explain_probe(probe_name: str) -> str: ...
def benchmark_probe_function(probe_func: Callable[[list[int]], Any], array: list[int]) -> float: ...
def benchmark_probe_by_name(probe_name: str, array: list[int]) -> float: ...
def max_for_size(probe_name: str, n: int) -> int: ...

__all__: list[str]
