def sort(sorter_name: str, array: list[float]) -> list[float]: ...
def benchmark_sorter(sorter_name: str, array: list[float]) -> float: ...
def list_sorters() -> list[str]: ...

__all__: list[str] = [
    "sort",
    "benchmark_sorter",
    "list_sorters",
]
